calling functio in itself is recursion.
